# Generated by Django 5.1.4 on 2026-08-27 02:18

import chatbot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_secret', models.CharField(default='', editable=False, max_length=64, unique=True)),
                ('chatealo_base_url', models.URLField(default='https://client.chatealo.io', verbose_name='URL base de la API de chatealo')),
                ('chatealo_account_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Account ID de chatealo')),
                ('chatealo_authorization', models.CharField(blank=True, default='', help_text='Valor del header "Authorization" que pide la API de chatealo.', max_length=300, verbose_name='Header Authorization')),
                ('chatealo_admin_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Header X-Chatealo-Admin-Id')),
                ('chatealo_user_token', models.CharField(blank=True, default='', max_length=100, verbose_name='Header X-AppChatealo-User-Token')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Chatbot',
                'verbose_name_plural': 'Configuración de Chatbot',
                'permissions': [('ver_panel_chatbot', 'Ver panel de configuración de Chatbot'), ('gestionar_token_chatbot', 'Editar la configuración y regenerar el secreto del webhook de Chatbot')],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.PositiveIntegerField(unique=True)),
                ('account_id', models.PositiveIntegerField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('label_equipo_actual', models.CharField(blank=True, help_text="Última etiqueta 'equipo-<slug>' aplicada, para poder reemplazarla por 'hist-...' si cambia.", max_length=110)),
                ('finalizado', models.BooleanField(default=False, help_text='True una vez derivada a un equipo.')),
                ('ultimo_message_id', models.PositiveIntegerField(blank=True, help_text='id del último mensaje de chatealo procesado, para ignorar reintentos duplicados del webhook.', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='DiaExcepcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado — cerrado todo el día'), ('ASUETO', 'Asueto — cerrado todo el día'), ('HORARIO_REDUCIDO', 'Horario reducido')], default='FERIADO', max_length=20)),
                ('hora_inicio', models.TimeField(blank=True, help_text='Solo para horario reducido.', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Solo para horario reducido.', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('sincronizado', models.BooleanField(default=False, editable=False, help_text='True si esta fila la generó la sincronización automática de feriados nacionales.')),
            ],
            options={
                'verbose_name': 'Día excepcional',
                'verbose_name_plural': 'Días excepcionales',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Desde')),
                ('hora_fin', models.TimeField(verbose_name='Hasta')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horario de atención',
                'verbose_name_plural': 'Horarios de atención',
                'ordering': ['dia_semana', 'hora_inicio'],
                'permissions': [('gestionar_horarios_chatbot', 'Configurar horarios y días excepcionales de atención de Chatbot')],
            },
        ),
        migrations.CreateModel(
            name='ArchivoChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=220, unique=True)),
                ('archivo', models.FileField(max_length=255, upload_to=chatbot.models.archivo_chatbot_path, verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Chatbot',
                'verbose_name_plural': 'Archivos de Chatbot',
                'ordering': ['-fecha_subida'],
                'permissions': [('gestionar_archivos_chatbot', 'Subir y eliminar archivos del repositorio de Chatbot')],
            },
        ),
        migrations.CreateModel(
            name='MenuOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Texto de la opción')),
                ('slug', models.SlugField(blank=True, help_text='Se autogenera del texto si se deja vacío. Se usa para las etiquetas menu-<slug> / equipo-<slug>.', max_length=100, unique=True)),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('tipo', models.CharField(choices=[('SUBMENU', 'Submenú — agrupa otras opciones'), ('RESPUESTA', 'Respuesta directa — el bot contesta un texto'), ('DERIVACION', 'Derivación — se deriva a un agente/área')], default='SUBMENU', max_length=12, verbose_name='Tipo')),
                ('respuesta_texto', models.TextField(blank=True, help_text='Texto que el bot devuelve al usuario cuando elige esta opción.', verbose_name='Texto de respuesta')),
                ('mensaje_derivacion', models.TextField(blank=True, help_text='Texto que el bot muestra al usuario al derivarlo (ej: horario de atención del área).', verbose_name='Mensaje al derivar')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivo', models.ForeignKey(blank=True, help_text='Se incluye su URL pública en la respuesta que recibe el bot.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.archivochatbot', verbose_name='Archivo adjunto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grupo_derivacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Área / equipo a derivar')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='chatbot.menuopcion', verbose_name='Submenú de')),
            ],
            options={
                'verbose_name': 'Opción de menú',
                'verbose_name_plural': 'Opciones de menú',
                'ordering': ['orden', 'texto'],
                'permissions': [('gestionar_menu_chatbot', 'Crear, editar y eliminar el menú de Chatbot')],
            },
        ),
        migrations.CreateModel(
            name='ConversacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_recibido', models.TextField(blank=True)),
                ('accion', models.CharField(choices=[('MENU', 'Bajó a un submenú'), ('RESPUESTA', 'Se respondió un texto'), ('DERIVACION', 'Se derivó a un equipo'), ('FUERA_HORARIO', 'Pidió un operador fuera de horario de atención'), ('INVALIDA', 'Opción no reconocida'), ('IGNORADO', 'Evento ignorado (no era mensaje de texto entrante)')], max_length=15)),
                ('detalle', models.TextField(blank=True, help_text='Ej: etiquetas aplicadas, errores de la API de chatealo.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='chatbot.conversacion')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chatbot.menuopcion')),
            ],
            options={
                'verbose_name': 'Log de conversación',
                'verbose_name_plural': 'Logs de conversación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='conversacion',
            name='menu_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chatbot.menuopcion', verbose_name='Submenú actual'),
        ),
    ]
