# Generated by Django 5.1.4 on 2026-08-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionlog',
            name='accion',
            field=models.CharField(choices=[('MENU', 'Navegó a un menú (submenú, volver o inicio)'), ('RESPUESTA', 'Se respondió un texto'), ('DERIVACION', 'Se derivó a un equipo'), ('TERMINAR', 'Terminó la conversación'), ('FUERA_HORARIO', 'Pidió un operador fuera de horario de atención'), ('INVALIDA', 'Opción no reconocida'), ('IGNORADO', 'Evento ignorado (no era mensaje de texto entrante)')], max_length=15),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='respuesta_texto',
            field=models.TextField(blank=True, help_text='Texto que el bot devuelve al usuario cuando elige esta opción. En Volver/Inicio/Terminar es opcional (si se deja vacío, no se manda mensaje extra).', verbose_name='Texto de respuesta'),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='tipo',
            field=models.CharField(choices=[('SUBMENU', 'Submenú — agrupa otras opciones'), ('RESPUESTA', 'Respuesta directa — el bot contesta un texto'), ('DERIVACION', 'Derivación — se deriva a un agente/área'), ('VOLVER', 'Volver al menú anterior'), ('INICIO', 'Ir al menú principal'), ('TERMINAR', 'Terminar la conversación')], default='SUBMENU', max_length=12, verbose_name='Tipo'),
        ),
    ]
