# Generated by Django 5.1.4 on 2026-08-27 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_conversacionlog_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionchatbot',
            name='archivo_despedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chatbot.archivochatbot', verbose_name='Archivo adjunto al despedirse'),
        ),
        migrations.AddField(
            model_name='configuracionchatbot',
            name='mensaje_despedida',
            field=models.TextField(blank=True, help_text='Texto único que mandan TODAS las opciones tipo "Terminar", sin importar en qué submenú estén. Si se deja vacío se usa un mensaje genérico por defecto.', verbose_name='Mensaje de despedida'),
        ),
    ]
