# Generated by Django 5.1.4 on 2026-08-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_configuracionchatbot_archivo_despedida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuopcion',
            name='respuesta_texto',
            field=models.TextField(blank=True, help_text='Texto que el bot devuelve al usuario cuando elige esta opción. En Volver/Inicio es opcional (si se deja vacío, no se manda mensaje extra). No se usa en Terminar: ese mensaje es único y vive en ConfiguracionChatbot.mensaje_despedida.', verbose_name='Texto de respuesta'),
        ),
    ]
