# Generated by Django 5.1.4 on 2026-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_menuopcion_respuesta_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuopcion',
            name='grupo_derivacion',
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='respuesta_texto',
            field=models.TextField(blank=True, help_text='Texto que el bot devuelve al usuario cuando elige esta opción. Solo aplica al tipo Respuesta: Submenú/Volver/Inicio navegan sin mensaje propio, y Terminar usa el mensaje único de ConfiguracionChatbot.mensaje_despedida.', verbose_name='Texto de respuesta'),
        ),
    ]
