# Generated by Django 5.1.4 on 2026-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_menuopcion_grupo_derivacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxChatealo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_id', models.PositiveIntegerField(unique=True, verbose_name='Inbox ID de chatealo')),
                ('nombre', models.CharField(blank=True, help_text='Nombre con el que se identifica esta bandeja en el panel.', max_length=120, verbose_name='Nombre')),
                ('tipo_fuente', models.CharField(blank=True, choices=[('WHATSAPP', 'WhatsApp'), ('WEBCHAT', 'Webchat'), ('TELEGRAM', 'Telegram'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('OTRO', 'Otro')], max_length=12, verbose_name='Tipo de fuente')),
                ('responder_bot', models.BooleanField(default=True, help_text='Si el bot debe responder a los eventos de esta bandeja. (El filtrado por bandeja todavía no está aplicado en el webhook.)')),
                ('nombre_detectado', models.CharField(blank=True, editable=False, max_length=200)),
                ('channel_detectado', models.CharField(blank=True, editable=False, max_length=100)),
                ('account_id', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('eventos_recibidos', models.PositiveIntegerField(default=0, editable=False)),
                ('primer_evento', models.DateTimeField(auto_now_add=True)),
                ('ultimo_evento', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Bandeja de chatealo',
                'verbose_name_plural': 'Bandejas de chatealo',
                'ordering': ['nombre', 'inbox_id'],
                'permissions': [('gestionar_inboxes_chatbot', 'Asociar nombre y tipo de fuente a las bandejas de Chatbot')],
            },
        ),
    ]
