# Generated by Django 5.1.4 on 2026-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_inboxchatealo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionchatbot',
            name='webhook_firma_enforce',
            field=models.BooleanField(default=False, help_text='Si está apagado, una firma que no valida sólo se registra en el log (modo observación); si está prendido, se responde 401 y no se procesa.', verbose_name='Rechazar eventos con firma inválida'),
        ),
        migrations.AddField(
            model_name='configuracionchatbot',
            name='webhook_firma_secret',
            field=models.CharField(blank=True, default='', help_text='Secreto que da chatealo para verificar la firma de los eventos entrantes.', max_length=200, verbose_name='Secreto de firma del webhook'),
        ),
    ]
