# Generated by Django 5.1.4 on 2026-08-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_configuracionchatbot_webhook_firma_enforce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('open', 'Abierta'), ('pending', 'Pendiente'), ('resolved', 'Resuelta'), ('snoozed', 'Pospuesta')], help_text="Último 'status' informado por chatealo (conversation_created / _status_changed).", max_length=20),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='inbox_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Inbox ID'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del contacto'),
        ),
        migrations.AlterField(
            model_name='conversacionlog',
            name='accion',
            field=models.CharField(choices=[('MENU', 'Navegó a un menú (submenú, volver o inicio)'), ('RESPUESTA', 'Se respondió un texto'), ('DERIVACION', 'Se derivó a un equipo'), ('TERMINAR', 'Terminó la conversación'), ('FUERA_HORARIO', 'Pidió un operador fuera de horario de atención'), ('INVALIDA', 'Opción no reconocida'), ('IGNORADO', 'Evento ignorado (no era mensaje de texto entrante)'), ('CONVERSACION', 'Evento de conversación (creada / cambió de estado)')], max_length=15),
        ),
    ]
