# Generated by Django 5.1.4 on 2026-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_conversacionlog_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionchatbot',
            name='plantilla_saludo_area',
            field=models.TextField(blank=True, help_text='Encabezado al entrar a un submenú. Usá {area} donde debe ir el nombre del área (el nombre va sin número; sólo las opciones se numeran). Si se deja vacío se usa uno por defecto.', verbose_name='Saludo de cada área / submenú'),
        ),
        migrations.AddField(
            model_name='configuracionchatbot',
            name='plantilla_saludo_inicial',
            field=models.TextField(blank=True, help_text='Encabezado del menú principal (antes del listado de opciones). Si se deja vacío se usa uno por defecto.', verbose_name='Saludo del menú principal'),
        ),
    ]
