# Generated by Django 5.1.4 on 2026-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_configuracionchatbot_plantilla_saludo_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='chatealo_resuelta',
            field=models.BooleanField(default=False, help_text='True si chatealo informó que la conversación quedó "resolved" después de derivarla/terminarla. Si el contacto vuelve a escribir, el bot se reactiva y muestra de nuevo el menú.'),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='finalizado',
            field=models.BooleanField(default=False, help_text='True una vez derivada a un equipo o terminada.'),
        ),
        migrations.AlterField(
            model_name='conversacionlog',
            name='accion',
            field=models.CharField(choices=[('MENU', 'Navegó a un menú (submenú, volver o inicio)'), ('RESPUESTA', 'Se respondió un texto'), ('DERIVACION', 'Se derivó a un equipo'), ('TERMINAR', 'Terminó la conversación'), ('FUERA_HORARIO', 'Pidió un operador fuera de horario de atención'), ('INVALIDA', 'Opción no reconocida'), ('IGNORADO', 'Evento ignorado (no era mensaje de texto entrante)'), ('CONVERSACION', 'Evento de conversación (creada / cambió de estado)'), ('MSG_FALLIDO', 'Un mensaje saliente falló (message_updated status=failed)'), ('REACTIVADA', 'El contacto volvió a escribir tras derivar/terminar: se reactivó el menú')], max_length=15),
        ),
    ]
