# Generated by Django 5.1.4 on 2026-08-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_conversacion_chatealo_resuelta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionchatbot',
            name='mensaje_bienvenida',
            field=models.TextField(blank=True, help_text='Se manda una sola vez, la primera vez que el contacto escribe, antes del menú. Sirve para aclarar que del otro lado hay un asistente automático. Si se deja vacío se usa uno por defecto.', verbose_name='Mensaje de bienvenida (primer contacto)'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='menu_mostrado',
            field=models.BooleanField(default=False, help_text='True una vez que el bot le mostró el menú al contacto al menos una vez. Mientras sea False, un mensaje que no matchea recibe el saludo de bienvenida (no "No entendí esa opción").'),
        ),
        migrations.AlterField(
            model_name='conversacionlog',
            name='accion',
            field=models.CharField(choices=[('MENU', 'Navegó a un menú (submenú, volver o inicio)'), ('RESPUESTA', 'Se respondió un texto'), ('DERIVACION', 'Se derivó a un equipo'), ('TERMINAR', 'Terminó la conversación'), ('FUERA_HORARIO', 'Pidió un operador fuera de horario de atención'), ('INVALIDA', 'Opción no reconocida'), ('IGNORADO', 'Evento ignorado (no era mensaje de texto entrante)'), ('CONVERSACION', 'Evento de conversación (creada / cambió de estado)'), ('MSG_FALLIDO', 'Un mensaje saliente falló (message_updated status=failed)'), ('REACTIVADA', 'El contacto volvió a escribir tras derivar/terminar: se reactivó el menú'), ('BIENVENIDA', 'Primer contacto: saludo de bienvenida + menú')], max_length=15),
        ),
    ]
