# Generated by Django 5.1.4 on 2026-08-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_configuracionchatbot_mensaje_bienvenida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionchatbot',
            name='mensaje_cierre_inactividad',
            field=models.TextField(blank=True, help_text='Se manda al cerrar una conversación por inactividad. Si se deja vacío se usa uno por defecto.', verbose_name='Mensaje de cierre por inactividad'),
        ),
        migrations.AddField(
            model_name='configuracionchatbot',
            name='minutos_inactividad_cierre',
            field=models.PositiveIntegerField(default=0, help_text='Si el contacto no escribe durante esta cantidad de minutos, el bot manda un mensaje de cierre y termina la conversación. 0 = desactivado.', verbose_name='Minutos de inactividad para cerrar la conversación'),
        ),
        migrations.AddField(
            model_name='configuracionchatbot',
            name='segundos_remostrar_menu',
            field=models.PositiveIntegerField(default=60, help_text='Después de contestar una opción de tipo Respuesta, esperar estos segundos y volver a mostrar el menú donde estaba el contacto. 0 = desactivado.', verbose_name='Segundos para volver a mostrar el menú tras una respuesta'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='remostrar_menu_en',
            field=models.DateTimeField(blank=True, help_text='Momento en que el temporizador debe volver a mostrar el menú actual (se agenda al responder una opción; se cancela si el contacto escribe antes).', null=True),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, help_text='Último mensaje entrante del contacto. Base para el cierre por inactividad.', null=True),
        ),
        migrations.AlterField(
            model_name='conversacionlog',
            name='accion',
            field=models.CharField(choices=[('MENU', 'Navegó a un menú (submenú, volver o inicio)'), ('RESPUESTA', 'Se respondió un texto'), ('DERIVACION', 'Se derivó a un equipo'), ('TERMINAR', 'Terminó la conversación'), ('FUERA_HORARIO', 'Pidió un operador fuera de horario de atención'), ('INVALIDA', 'Opción no reconocida'), ('IGNORADO', 'Evento ignorado (no era mensaje de texto entrante)'), ('CONVERSACION', 'Evento de conversación (creada / cambió de estado)'), ('MSG_FALLIDO', 'Un mensaje saliente falló (message_updated status=failed)'), ('REACTIVADA', 'El contacto volvió a escribir tras derivar/terminar: se reactivó el menú'), ('BIENVENIDA', 'Primer contacto: saludo de bienvenida + menú'), ('INACTIVIDAD', 'Cerrada por inactividad')], max_length=15),
        ),
    ]
