# Generated by Django 5.1.4 on 2026-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_grupo_admin_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionchatbot',
            name='mensaje_bienvenida',
            field=models.TextField(blank=True, help_text='Se manda una sola vez, la primera vez que el contacto escribe, antes del menú. Sirve para aclarar que del otro lado hay un asistente automático. Variable disponible: {nombre}. Si se deja vacío se usa uno por defecto.', verbose_name='Mensaje de bienvenida (primer contacto)'),
        ),
        migrations.AlterField(
            model_name='configuracionchatbot',
            name='mensaje_cierre_inactividad',
            field=models.TextField(blank=True, help_text='Se manda al cerrar una conversación por inactividad. Variable disponible: {nombre}. Si se deja vacío se usa uno por defecto.', verbose_name='Mensaje de cierre por inactividad'),
        ),
        migrations.AlterField(
            model_name='configuracionchatbot',
            name='mensaje_despedida',
            field=models.TextField(blank=True, help_text='Texto único que mandan TODAS las opciones tipo "Terminar", sin importar en qué submenú estén. Variable disponible: {nombre}. Si se deja vacío se usa un mensaje genérico por defecto.', verbose_name='Mensaje de despedida'),
        ),
        migrations.AlterField(
            model_name='configuracionchatbot',
            name='plantilla_saludo_area',
            field=models.TextField(blank=True, help_text='Encabezado al entrar a un submenú. Variables: {area} (nombre del área, sin número) y {nombre} (nombre del contacto). Si se deja vacío se usa uno por defecto.', verbose_name='Saludo de cada área / submenú'),
        ),
        migrations.AlterField(
            model_name='configuracionchatbot',
            name='plantilla_saludo_inicial',
            field=models.TextField(blank=True, help_text='Encabezado del menú principal (antes del listado de opciones). Variable disponible: {nombre}. Si se deja vacío se usa uno por defecto.', verbose_name='Saludo del menú principal'),
        ),
    ]
