# Generated by Django 5.1.4 on 2026-08-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_alter_configuracionchatbot_mensaje_bienvenida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionchatbot',
            name='mensaje_despedida',
            field=models.TextField(blank=True, help_text='Texto único que mandan TODAS las opciones tipo "Terminar", sin importar en qué menú estén. Variable disponible: {nombre}. Si se deja vacío se usa un mensaje genérico por defecto.', verbose_name='Mensaje de despedida'),
        ),
        migrations.AlterField(
            model_name='configuracionchatbot',
            name='plantilla_saludo_area',
            field=models.TextField(blank=True, help_text='Encabezado al entrar a un menú. Variables: {area} (nombre del menú, sin número) y {nombre} (nombre del contacto). Si se deja vacío se usa uno por defecto.', verbose_name='Saludo de cada menú'),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='menu_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chatbot.menuopcion', verbose_name='Menú actual'),
        ),
        migrations.AlterField(
            model_name='conversacionlog',
            name='accion',
            field=models.CharField(choices=[('MENU', 'Navegó a un menú (o volver / inicio)'), ('RESPUESTA', 'Se respondió un texto'), ('DERIVACION', 'Se derivó a un equipo'), ('TERMINAR', 'Terminó la conversación'), ('FUERA_HORARIO', 'Pidió un operador fuera de horario de atención'), ('INVALIDA', 'Opción no reconocida'), ('IGNORADO', 'Evento ignorado (no era mensaje de texto entrante)'), ('CONVERSACION', 'Evento de conversación (creada / cambió de estado)'), ('MSG_FALLIDO', 'Un mensaje saliente falló (message_updated status=failed)'), ('REACTIVADA', 'El contacto volvió a escribir tras derivar/terminar: se reactivó el menú'), ('BIENVENIDA', 'Primer contacto: saludo de bienvenida + menú'), ('INACTIVIDAD', 'Cerrada por inactividad')], max_length=15),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='chatbot.menuopcion', verbose_name='Dentro del menú'),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='respuesta_texto',
            field=models.TextField(blank=True, help_text='Texto que el bot devuelve al usuario cuando elige esta opción. Solo aplica al tipo Respuesta: Menú/Volver/Inicio navegan sin mensaje propio, y Terminar usa el mensaje único de ConfiguracionChatbot.mensaje_despedida.', verbose_name='Texto de respuesta'),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='tipo',
            field=models.CharField(choices=[('SUBMENU', 'Menú — agrupa otras opciones'), ('RESPUESTA', 'Respuesta directa — el bot contesta un texto'), ('DERIVACION', 'Derivación — se deriva a un agente/área'), ('VOLVER', 'Volver al menú anterior'), ('INICIO', 'Ir al menú principal'), ('TERMINAR', 'Terminar la conversación')], default='SUBMENU', max_length=12, verbose_name='Tipo'),
        ),
    ]
