# Generated by Django 5.1.4 on 2026-08-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_alter_configuracionchatbot_mensaje_despedida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionchatbot',
            name='activo',
            field=models.BooleanField(default=True, help_text='Interruptor general. Si se apaga, el bot NO responde ningún mensaje (los eventos se siguen recibiendo pero se ignoran). Útil mientras se configura el menú.', verbose_name='Bot activo'),
        ),
        migrations.AlterField(
            model_name='conversacionlog',
            name='accion',
            field=models.CharField(choices=[('MENU', 'Navegó a un menú (o volver / inicio)'), ('RESPUESTA', 'Se respondió un texto'), ('DERIVACION', 'Se derivó a un equipo'), ('TERMINAR', 'Terminó la conversación'), ('FUERA_HORARIO', 'Pidió un operador fuera de horario de atención'), ('INVALIDA', 'Opción no reconocida'), ('IGNORADO', 'Evento ignorado (no era mensaje de texto entrante)'), ('CONVERSACION', 'Evento de conversación (creada / cambió de estado)'), ('MSG_FALLIDO', 'Un mensaje saliente falló (message_updated status=failed)'), ('REACTIVADA', 'El contacto volvió a escribir tras derivar/terminar: se reactivó el menú'), ('BIENVENIDA', 'Primer contacto: saludo de bienvenida + menú'), ('INACTIVIDAD', 'Cerrada por inactividad'), ('PAUSADO', 'Llegó un mensaje con el bot pausado desde el panel')], max_length=15),
        ),
    ]
