# Generated by Django 5.1.4 on 2026-09-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_alter_configuracionchatbot_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuopcion',
            name='boton_texto',
            field=models.CharField(blank=True, help_text='Solo Respuesta. Botón de acción al pie del mensaje. Máx. 20 caracteres (límite de WhatsApp). Necesita también el link cargado.', max_length=20, verbose_name='Texto del botón'),
        ),
        migrations.AddField(
            model_name='menuopcion',
            name='boton_url',
            field=models.URLField(blank=True, help_text='A dónde lleva el botón (debe empezar con https://). Necesita también el texto.', verbose_name='Link del botón'),
        ),
    ]
