# Generated by Django 5.1.4 on 2026-09-10 18:52

from django.db import migrations, models


def _migrar_derivaciones_cargadas(apps, schema_editor):
    """Las opciones tipo DERIVACION cargadas a mano pasan a ser el mensaje de
    derivación del menú que las contenía (ahora "Hablar con un operador" es una
    opción fija y configurable por menú), y después se borran."""
    MenuOpcion = apps.get_model('chatbot', 'MenuOpcion')
    for op in MenuOpcion.objects.filter(tipo='DERIVACION'):
        padre = op.parent
        if padre and op.mensaje_derivacion and not padre.mensaje_derivacion:
            padre.mensaje_derivacion = op.mensaje_derivacion
            padre.save(update_fields=['mensaje_derivacion'])
    MenuOpcion.objects.filter(tipo='DERIVACION').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_alter_menuopcion_tipo'),
    ]

    operations = [
        migrations.RunPython(_migrar_derivaciones_cargadas, migrations.RunPython.noop),
        migrations.AddField(
            model_name='configuracionchatbot',
            name='derivacion_mensaje',
            field=models.TextField(blank=True, help_text='Texto que recibe el contacto al pedir un operador. Variables: {area}, {nombre}. Si se deja vacío se usa uno genérico. Cada submenú puede tener el suyo.', verbose_name='Mensaje al derivar a un operador'),
        ),
        migrations.AddField(
            model_name='configuracionchatbot',
            name='derivacion_ofrecer',
            field=models.BooleanField(default=True, help_text='Si se apaga, el menú principal no ofrece derivación a un operador. Cada submenú tiene su propio interruptor.', verbose_name='Ofrecer "Hablar con un operador" en el menú principal'),
        ),
        migrations.AddField(
            model_name='configuracionchatbot',
            name='derivacion_texto',
            field=models.CharField(blank=True, help_text='Cómo aparece la opción en el listado. Máx. 24 caracteres (límite de WhatsApp). Si se deja vacío: "Hablar con un operador".', max_length=24, verbose_name='Texto de la opción de operador'),
        ),
        migrations.AddField(
            model_name='menuopcion',
            name='derivacion_ofrecer',
            field=models.BooleanField(default=True, help_text='Sólo aplica al tipo Menú. Si se apaga, este menú no ofrece derivación a un operador.', verbose_name='Ofrecer "Hablar con un operador" en este menú'),
        ),
        migrations.AddField(
            model_name='menuopcion',
            name='derivacion_texto',
            field=models.CharField(blank=True, help_text='Sólo Menú. Cómo aparece la opción en este menú. Máx. 24 caracteres. Si se deja vacío se usa el texto general.', max_length=24, verbose_name='Texto de la opción de operador'),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='mensaje_derivacion',
            field=models.TextField(blank=True, help_text='Sólo Menú. Texto que recibe el contacto al pedir un operador desde este menú (ej: horario de atención del área). Variables: {area}, {nombre}. Si se deja vacío se usa el mensaje general.', verbose_name='Mensaje al derivar a un operador'),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='respuesta_texto',
            field=models.TextField(blank=True, help_text='Sólo tipo Respuesta: el texto que el bot devuelve al elegir esta opción. Un Menú sólo muestra su listado; la despedida y la derivación se configuran aparte.', verbose_name='Texto de respuesta'),
        ),
        migrations.AlterField(
            model_name='menuopcion',
            name='tipo',
            field=models.CharField(choices=[('SUBMENU', 'Menú — agrupa otras opciones'), ('RESPUESTA', 'Respuesta directa — el bot contesta un texto')], default='SUBMENU', max_length=12, verbose_name='Tipo'),
        ),
    ]
