# Generated by Django 5.1.4 on 2026-09-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_configuracionchatbot_derivacion_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionchatbot',
            name='derivacion_equipo',
            field=models.SlugField(blank=True, help_text='Slug del equipo de chatealo (se aplica como etiqueta "equipo-<slug>"). Si se deja vacío, desde el menú principal se usa "equipo-general".', max_length=100, verbose_name='Equipo al que se transfiere (menú principal)'),
        ),
        migrations.AddField(
            model_name='menuopcion',
            name='derivacion_equipo',
            field=models.SlugField(blank=True, help_text='Sólo Menú. Slug del equipo de chatealo (etiqueta "equipo-<slug>"). Si se deja vacío se usa el slug de este menú.', max_length=100, verbose_name='Equipo al que se transfiere'),
        ),
    ]
